rules:
  indent:
    - 2
    - 2
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
env:
  node: true
  browser: true
extends: 'eslint:recommended'
ecmaFeatures:
  jsx: true
  experimentalObjectRestSpread: true
plugins:
  - html
  - json
